language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=pypy
  - TOXENV=py34

install:
  - pip install -q tox
  - sudo apt-get install lrzsz

script:
  - tox -e $TOXENV

notifications:
  email:
    - contact@jeffquast.com
    - maze@pyth0n.org
